language: node_js
dist: trusty
node_js: stable
before_script:
- npm install --silent bower polymer-cli
- bower install --silent
addons:
  sauce_connect: true
script:
- npm run lint
- node_modules/.bin/polymer test --plugin sauce --job-name "code-mirror:${TRAVIS_BRANCH}"
  --build-number=${TRAVIS_BUILD_NUMBER}
cache:
  directories:
  - bower_components
  - node_modules
branches:
  only:
  - stage
  - develop
after_success:
- node tasks/ci.js
env:
  global:
  - secure: eAxdfMLS5aF7NylX7MYwWoUYvbgOl+3SIS5EYfAEPedVCW6YRkDwF7xyFbOcVDJuyhpXkxxy50/NyZKENFGGS6pXJXgf6whCrnPFbwpLC1/Q+L0yogSoe3AtZK/fYXGPit+9PXmL94II2sTWA/dw/dbpIiQIKMVULxvPk1O2VMWJPhpGvx7pFqHthjOcBDRXZmwF2qFbwlKQ/qhYTJIJPu0ZBIeuUNDoThJGdAQ9PtfQ5+LSLlok1rF/2n4YdwysfhrStsU+bQNosD69DgzZjSd9N9YCIRoUqQoWig59XyRlvIKbIkx6uyTBIK4n6rDZuccHNIOmQwUT2Fn5v+79w3/DvaIhfFsJ++Ezy1ZEJ5H3VJEiJBb5wPcFTBqV6F+wiNRN6aVDg6hZwfN8yoXe+IlDf0FOQR102yp8Ve9nv02/D0u5rWW7VV3uDVDCzOa+wjWY7IHaHJ0cbeUny1VpfD3CAVHF/thyLFJdtjysSl4KpatXLY2uqpFu46/4lGlUOJBdesYhWVPqKGWlTlYDAhvtQH2509IAQ0jkz5dUSBfFTQGgm10q6Xzq9Qap299HNxaaSlv8XLVfSryrUkk3vhhVuKlZ9S/mKH0F+whjagucVca2+x7IhvPjnxKgE13NgMWkycL3aQCudN9DAcFj8oirh7SMiJvhMa5+y4VG3mM=
  - secure: du1Sho5+gIFPGawuN7noLRvesHnHSAu8taDBdUAodJhyM+JlF6HLOgCHLH/PZJjr/5mFpqMdFM9tkVQ0GvSvR+amgQ/hjkU0u2McpNDjvmNZI9wx3x9pkplmULQxh4NyuCysChdcTNdAEqVE8N4Ti+MHzq+Rko1QOn3Sl42xzElq89oSJYakWeolAkPPzJx7IlOF/3tpwOcoyUwp7ZBZPtEOzPAoHswhDUzd0FpgqTkAlYAXEXnAlEznfK5SQNAyU7SZUFbBu2DrDh/7N3knJ1fOeau9jwk+r6EHu1sav9acuowKs0yyr9O+PmRoR32jn7R6UQ1WvBMH96NmtrkfhLEeHaMrV8kQoQErZUUGHD9RoW5JBRrcX9C00ICX4dv9lci+4s756+IXnSRLy5dWStcxmcMTkN3ERNvZONoUy3S0OW9y3zmzJtQo7YCSs6Fc6pUbyhyZu6SBk97T+Yy7ynsf9wsuKMVhBiX5NFzQShIduPFBRKdbGDy6BwM7+lXTl1tvZbY9mPZY8crRDQ5djGFy45SjAm8AeMEcvadlVlGEmSkK3Al7/QQcHQUFqbLZtE1x463NLiimtcHsAUFdo7KRNay+D0AeknFloO2OTMBN/b8/hqBZKcVcAxOE1qRGBBTsSy8Te3XnhRTLdbMyqdgCJ0+neArZd+sJNE+QLK4=
